apiVersion: v1
metadata:
  name: {{ template "flokkr.fullname" . }}-datasources
  labels:
{{ include "flokkr.commonlabels" . | indent 6}}
data:
  prometheus.yaml: |-
   apiVersion: 1
   datasources:
   - name: prometheus
     type: prometheus
     access: proxy
     orgId: 1
     url: {{ .Values.prometheusurl }}
     version: 1
     editable: false
kind: ConfigMap

