apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "flokkr.fullname" . }}-dashboard-watcher
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "flokkr.fullname" . }}-dashboard-watcher-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ template "flokkr.fullname" . }}-dashboard-watcher
  namespace: {{ .Release.Namespace }}
