image:
  tag: &tag latest
  pullPolicy: Always
  repository: flokkr/zookeeper

features:
  prometheus: true

env: {}

services:
   zookeeper:
      replicas: 3

config:
  zoo:
    tickTime: 2000
    dataDir: /data/zookeeper
    clientPort: 2181
    initLimit: 5
    syncLimit: 2    
  log4j:
    log4j.rootLogger: "INFO, stdout"
    log4j.appender.stdout: org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout: org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n"
