image:
  tag: &tag ozone
  pullPolicy: Always
  repository: flokkr/hadoop

component:
   hdsl: true
   ozone: true

serviceAccount: cblock

features:
  prometheus: true
  grafana: true

env: {}

services:
   datanode:
      replicas: 3

config:
  coreSite: {}
  ozoneSite:
    ozone.enabled: True
    ozone.scm.datanode.id: /data/datanode.id
    ozone.metadata.dirs: /data/metadata
    rpc.metrics.quantile.enable: true
    rpc.metrics.percentiles.intervals: 60,300
  hdfsSite: {}
  log4j:
    log4j.rootLogger: "INFO, stdout"
    log4j.appender.stdout: org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout: org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n"


keel:
  policy: force
  trigger: poll
  pollSchedule: "@every 3m"
  images:
    - repository: image.repository
      tag: image.tag
