apiVersion: v1

metadata:
  name: {{ template "flokkr.fullname" . }}-config
  labels:
{{ include "flokkr.commonlabels" . | indent 4}}
data:
  core-site.xml: |-
    <configuration>
    <property><name>fs.defaultFS</name><value>hdfs://{{ template "flokkr.fullname" . }}-hdfs-namenode-0.{{ template "flokkr.fullname" . }}-hdfs-namenode:9000</value></property>
{{ if .Values.feature.kerberos }}
    <property><name>dfs.data.transfer.protection</name><value>authentication</value></property>
    <property><name>hadoop.security.authentication</name><value>kerberos</value></property>
    <property><name>hadoop.security.auth_to_local</name><value>RULE:[2:$1@$0](.*)s/.*/root/</value></property>
{{end}}
    </configuration>
  mapred-site.xml: |-
    <configuration>
    <property><name>mapreduce.framework.name</name><value>yarn</value></property>
    <property><name>mapreduce.reduce.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
    <property><name>mapreduce.map.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
    <property><name>yarn.app.mapreduce.am.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
    </configuration>
  hdfs-site.xml: |-
    <configuration>
    <property><name>dfs.namenode.rpc-address</name><value>{{ template "flokkr.fullname" . }}-hdfs-namenode-0.{{ template "flokkr.fullname" . }}-hdfs-namenode:9000</value></property>
    <property><name>dfs.replication</name><value>3</value></property>
    <property><name>dfs.permissions.superusergroup</name><value>admin</value></property>
    <property><name>dfs.datanode.data.dir</name><value>/data/datanode</value></property>
    <property><name>dfs.namenode.name.dir</name><value>/data/namenode</value></property>
    <property><name>dfs.namenode.http-bind-host</name><value>0.0.0.0</value></property>
    <property><name>dfs.namenode.datanode.registration.ip-hostname-check</name><value>false</value></property>

{{ if .Values.feature.kerberos }}
    <property><name>dfs.namenode.keytab.file</name><value>/tmp/nn.keytab</value></property>
    <property><name>dfs.web.authentication.kerberos.keytab</name><value>/tmp/HTTP.keytab</value></property>
    <property><name>dfs.block.access.token.enable</name><value>true</value></property>
    <property><name>dfs.block.access.key.update.interval</name><value>5</value></property>

    <property><name>dfs.web.authentication.kerberos.principal</name><value>HTTP/_HOST@EXAMPLE.COM</value></property>
    <property><name>dfs.datanode.kerberos.principal</name><value>dn/_HOST@EXAMPLE.COM</value></property>
    <property><name>dfs.namenode.kerberos.principal</name><value>nn/{{ template "flokkr.fullname" . }}-hdfs-namenode-0.{{ template "flokkr.fullname" . }}-hdfs-namenode.default.svc.cluster.local@EXAMPLE.COM</value></property>

    <property><name>dfs.block.access.token.lifetime</name><value>10</value></property>
    <property><name>dfs.http.policy</name><value>HTTPS_ONLY</value></property>
    <property><name>dfs.replication</name><value>1</value></property>
    <property><name>dfs.datanode.keytab.file</name><value>/tmp/dn.keytab</value></property>
    <property><name>dfs.data.transfer.protection</name><value>authentication</value></property>
{{end}}
    </configuration>
  log4j.properties: |-
    log4j.rootLogger: TRACE,stdout
    log4j.appender.stdout: org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout: org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern: %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
  yarn-site.xml: |-
    <configuration>
    <property><name>yarn.resourcemanager.hostname</name><value>{{ template "flokkr.fullname" . }}-yarn-resourcemanager-0.{{ template "flokkr.fullname" . }}-yarn-resourcemanager</value></property>
    <property><name>yarn.nodemanager.pmem-check-enabled</name><value>false</value></property>
    <property><name>yarn.nodemanager.delete.debug-delay-sec</name><value>600</value></property>
    <property><name>yarn.nodemanager.vmem-check-enabled</name><value>false</value></property>
    <property><name>yarn.nodemanager.aux-services</name><value>mapreduce_shuffle</value></property>
    <property><name>yarn.nodemanager.delete.thread-count</name><value>0</value></property>
    <property><name>yarn.nodemanager.local-dirs</name><value>/data/nodemanagerlocaldir</value></property>
    <property><name>yarn.nodemanager.log-dirs</name><value>/data/yarn-userlogs</value></property>
    <property><name>yarn.nodemanager.remote-app-log-dir</name><value>/data/yarn-remotelogs</value></property>
    <property><name>yarn.resourcemanager.bind-host</name><value>0.0.0.0</value></property>
    <property><name>yarn.nodemanager.bind-host</name><value>0.0.0.0</value></property>
    <property><name>yarn.scheduler.maximum-allocation-mb</name><value>12000</value></property>
    <property><name>yarn.nodemanager.resource.memory-mb</name><value>12000</value></property>
    <property><name>yarn.webapp.ui2.enable</name><value>true</value></property>
    </configuration>
  capacity-scheduler.xml: |-
    <configuration>
    <property><name>yarn.scheduler.capacity.node-locality-delay</name><value>40</value></property>
    <property><name>yarn.scheduler.capacity.root.default.user-limit-factor</name><value>1</value></property>
    <property><name>yarn.scheduler.capacity.root.default.acl_submit_applications</name><value>*</value></property>
    <property><name>yarn.scheduler.capacity.maximum-applications</name><value>10000</value></property>
    <property><name>yarn.scheduler.capacity.maximum-am-resource-percent</name><value>0.1</value></property>
    <property><name>yarn.scheduler.capacity.queue-mappings-override.enable</name><value>false</value></property>
    <property><name>yarn.scheduler.capacity.root.queues</name><value>default</value></property>
    <property><name>yarn.scheduler.capacity.root.default.state</name><value>RUNNING</value></property>
    <property><name>yarn.scheduler.capacity.queue-mappings</name><value></value></property>
    <property><name>yarn.scheduler.capacity.root.default.maximum-capacity</name><value>100</value></property>
    <property><name>yarn.scheduler.capacity.root.default.capacity</name><value>100</value></property>
    <property><name>yarn.scheduler.capacity.root.default.acl_administer_queue</name><value>*</value></property>
    <property><name>yarn.scheduler.capacity.resource-calculator</name><value>org.apache.hadoop.yarn.util.resource.DefaultResourceCalculator</value></property>
    </configuration>
{{ if .Values.feature.kerberos }}
  ssl-client.xml: |-
     <configuration>
     <property><name>ssl.server.keystore.location</name><value>/opt/hadoop/etc/hadoop/hadoop.keystore</value></property>
     <property><name>ssl.server.truststore.password</name><value>Welcome1</value></property>
     <property><name>ssl.server.truststore.location</name><value>/tmp/truststore</value></property>
     <property><name>ssl.server.keystore.keypassword</name><value>Welcome1</value></property>
     <property><name>ssl.server.keystore.password</name><value>Welcome1</value></property>
     </configuration>
  ssl-server.xml: |-
     <configuration>
     <property><name>ssl.server.keystore.location</name><value>/tmp/hadoop.keystore</value></property>
     <property><name>ssl.server.truststore.password</name><value>Welcome1</value></property>
     <property><name>ssl.server.truststore.location</name><value>/tmp/truststore</value></property>
     <property><name>ssl.server.keystore.keypassword</name><value>Welcome1</value></property>
     <property><name>ssl.server.keystore.password</name><value>Welcome1</value></property>
     </configuration>
{{end}}
kind: ConfigMap
