apiVersion: v1
kind: Service
metadata:
  name: {{ template "flokkr.fullname" . }}-hdfs-namenode
  labels:
{{ include "flokkr.commonlabels" . | indent 4}}
spec:
  ports:
  - port: 9870
    name: web
  clusterIP: None
  selector:
     app: {{ template "flokkr.fullname" . }}
     component: hdfs-namenode
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "flokkr.fullname" . }}-hdfs-namenode
  labels:
{{ include "flokkr.commonlabels" . | indent 4}}
spec:
  serviceName: {{ template "flokkr.fullname" . }}-hdfs-namenode
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "flokkr.fullname" . }}
        component: hdfs-namenode
{{ include "flokkr.commonlabels" . | indent 8}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      containers:
        - name: hdfs-namenode
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          args: ["hdfs","namenode"]
          env:
            - name: ENSURE_NAMENODE_DIR
              value: /data/namenode
{{ if .Values.feature.kerberos }}
            - name: HADOOP_OPTS
              value: "-Dsun.security.krb5.debug=true"
            - name: KRB5_TRACE
              value: "/tmp/kinit.log"
            - name: LAUNCHER_UPDATE
              value: "true"
            - name: LAUNCHER_GITREF
              value: "origin/master"
            - name: CONF_DIR
              value: /tmp
            - name: KERBEROS_KEYTABS
              value: nn HTTP
            - name: KERBEROS_KEYSTORES
              value: hadoop
            - name: KERBEROS_SERVER
              value: krb5-0.krb5
{{end}}
{{ include "prometheus.jmx" . | indent 12}}
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
      volumes:
        - name: config
          configMap:
            name: {{ template "flokkr.fullname" . }}-config
