{{ if .Values.service.datanode.daemonset }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "flokkr.fullname" . }}-hdfs-datanode
  labels:
{{ include "flokkr.commonlabels" . | indent 6}}
spec:
  template:
    metadata:
      labels:
        component: hdfs-datanode
{{ include "flokkr.commonlabels" . | indent 8}}
    spec:
      containers:
        - name: hdfs-datanode
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          args: ["hdfs","datanode"]
          env:
            - name: HADOOP_OPTS
              value:
{{ if .Values.feature.kerberos }}
            - name: CONF_DIR
              value: /tmp
            - name: KERBEROS_KEYTABS
              value: dn HTTP
            - name: KERBEROS_KEYSTORES
              value: hadoop
            - name: KERBEROS_SERVER
              value: krb5-0.krb5
{{end}}
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "flokkr.fullname" . }}-config
{{end}}
