{{ if .Values.service.nodemanager.daemonset }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "flokkr.fullname" . }}-yarn-nodemanager
  labels:
{{ include "flokkr.commonlabels" . | indent 6}}
spec:
  template:
    metadata:
      labels:
        component: yarn-nodemanager
{{ include "flokkr.commonlabels" . | indent 8}}
    spec:
      containers:
        - name: yarn-nodemanager
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          args: ["yarn","nodemanager"]
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "flokkr.fullname" . }}-config
{{end}}
