{{ if not .Values.service.nodemanager.daemonset }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "flokkr.fullname" . }}-yarn-nodemanager
  labels:
{{ include "flokkr.commonlabels" . | indent 6}}
spec:
  ports:
  - port: 9874
    name: web
  clusterIP: None
  selector:
     app: {{ template "flokkr.fullname" . }}
     component: yarn-nodemanager
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "flokkr.fullname" . }}-yarn-nodemanager
spec:
  serviceName: {{ template "flokkr.fullname" . }}-yarn-nodemanager
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        component: yarn-nodemanager
{{ include "flokkr.commonlabels" . | indent 8}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: {{ template "flokkr.fullname" . }}
                  component: yarn-resourcemanager
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: yarn-nodemanager
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          args: ["yarn","nodemanager"]
          env:
{{ include "prometheus.jmx" . | indent 12}}
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "flokkr.fullname" . }}-config
{{end}}
