apiVersion: v1
kind: Service
metadata:
  name: {{ template "flokkr.fullname" . }}-zeppelin
  labels:
{{ include "flokkr.commonlabels" . | indent 6}}
spec:
  ports:
  - port: 8080
    name: web
  clusterIP: None
  selector:
     app: {{ template "flokkr.fullname" . }}
     component: zeppelin
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "flokkr.fullname" . }}-zeppelin
spec:
  serviceName: {{ template "flokkr.fullname" . }}-zeppelin
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        component: zeppelin
{{ include "flokkr.commonlabels" . | indent 8}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      containers:
        - name: zeppelin
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          env:
{{ include "prometheus.jmx" . | indent 12}}
#          volumeMounts:
#            - name: config
#              mountPath: "/opt/zeppelin/conf"
#              readOnly: true
#      volumes:
#        - name: config
#          configMap:
#            name: {{ template "flokkr.fullname" . }}-config
