apiVersion: v1
kind: Service
metadata:
  name: {{ template "flokkr.fullname" . }}
  labels:
{{ include "flokkr.commonlabels" . | indent 4}}
spec:
  ports:
  - port: 8081
    name: issuer
  clusterIP: None
  selector:
     app: {{ template "flokkr.fullname" . }}
     component: krb5
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "flokkr.fullname" . }}
  labels:
{{ include "flokkr.commonlabels" . | indent 4}}
spec:
  serviceName: {{ template "flokkr.fullname" . }}
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "flokkr.fullname" . }}
        component: krb5
{{ include "flokkr.commonlabels" . | indent 8}}
    spec:
      containers:
        - name: krb5
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
