apiVersion: v1
metadata:
  name: {{ template "flokkr.fullname" . }}-config
  labels:
{{ include "flokkr.commonlabels" . | indent 6}}
data:
  core-site.xml: |-
    <configuration>
      <property><name>fs.defaultFS</name><value>hdfs://{{ template "flokkr.fullname" . }}-hdfs-namenode-0.{{ template "flokkr.fullname" . }}-hdfs-namenode:9000</value></property>
    </configuration>
  hdfs-site.xml: |-
    <configuration>
    <property><name>dfs.namenode.rpc-address</name><value>{{ template "flokkr.fullname" . }}-hdfs-namenode-0.{{ template "flokkr.fullname" . }}-hdfs-namenode:9000</value></property>
    <property><name>dfs.replication</name><value>3</value></property>
    <property><name>dfs.permissions.superusergroup</name><value>admin</value></property>
    <property><name>dfs.datanode.data.dir</name><value>/data/datanode</value></property>
    <property><name>dfs.namenode.name.dir</name><value>/data/namenode</value></property>
    <property><name>dfs.namenode.http-bind-host</name><value>0.0.0.0</value></property>
    <property><name>dfs.datanode.plugins</name><value>org.apache.hadoop.ozone.HddsDatanodeService</value></property>
    <property><name>dfs.namenode.datanode.registration.ip-hostname-check</name><value>false</value></property>
    <property><name>rpc.metrics.quantile.enable</name><value>true</value></property>
    <property><name>rpc.metrics.percentiles.intervals</name><value>60,300</value></property>   
    </configuration>
  log4j.properties: |-
    log4j.rootLogger: INFO, stdout
    log4j.appender.stdout: org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout: org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern: %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
  ozone-site.xml: |-
    <configuration>
    <property><name>ozone.scm.block.client.address</name><value>{{ template "flokkr.fullname" . }}-ozone-scm-0.{{ template "flokkr.fullname" . }}-ozone-scm</value></property>
    <property><name>ozone.handler.type</name><value>distributed</value></property>
    <property><name>ozone.om.address</name><value>{{ template "flokkr.fullname" . }}-ozone-om-0.{{ template "flokkr.fullname" . }}-ozone-om</value></property>
    <property><name>ozone.enabled</name><value>True</value></property>
    <property><name>ozone.scm.datanode.id</name><value>/data/datanode.id</value></property>
    <property><name>ozone.scm.client.address</name><value>{{ template "flokkr.fullname" . }}-ozone-scm-0.{{ template "flokkr.fullname" . }}-ozone-scm</value></property>
    <property><name>ozone.metadata.dirs</name><value>/data/metadata</value></property>
    <property><name>ozone.scm.names</name><value>{{ template "flokkr.fullname" . }}-ozone-scm-0.{{ template "flokkr.fullname" . }}-ozone-scm</value></property>
    <property><name>dfs.cblock.iscsi.advertised.ip</name><value>{{ .Values.service.iscsi.ClusterIp }}</value></property>
    <property><name>dfs.cblock.jscsi.cblock.server.address</name><value>{{ template "flokkr.fullname" . }}-quadra-master-0.{{ template "flokkr.fullname" . }}-quadra-master</value></property>
    <property><name>dfs.cblock.scm.ipaddress</name><value>{{ template "flokkr.fullname" . }}-ozone-scm-0.{{ template "flokkr.fullname" . }}-ozone-scm</value></property>
    <property><name>dfs.cblock.service.leveldb.path</name><value>/data/cb</value></property>
    <property><name>dfs.cblock.short.circuit.io</name><value>true</value></property>
    <property><name>dfs.cblock.kubernetes.dynamic-provisioner.enabled</name><value>true</value></property>
    </configuration>
kind: ConfigMap
