apiVersion: v1
metadata:
  name: {{ template "flokkr.fullname" . }}-config
  labels:
{{ include "flokkr.commonlabels" . | indent 6}}
data:
  core-site.xml: |-
    <configuration>
      <property><name>fs.defaultFS</name><value>hdfs://{{ template "flokkr.fullname" . }}-hdfs-namenode-0.{{ template "flokkr.fullname" . }}-hdfs-namenode:9000</value></property>
      {{- range $key, $value := .Values.config.coreSite }}
        <property><name>{{ $key }}</name><value>{{ $value }}</value></property>
      {{- end }}
    </configuration>
  hdfs-site.xml: |-
    <configuration>
    <property><name>dfs.namenode.rpc-address</name><value>{{ template "flokkr.fullname" . }}-hdfs-namenode-0.{{ template "flokkr.fullname" . }}-hdfs-namenode:9000</value></property>
    {{- range $key, $value := .Values.config.hdfsSite }}
      <property><name>{{ $key }}</name><value>{{ $value }}</value></property>
    {{- end }}
    </configuration>
  log4j.properties: |-
    {{- range $key, $value := .Values.config.log4j }}
      {{ $key }}: {{ $value }}
    {{- end }}
  ozone-site.xml: |-
    <configuration>
    <property><name>ozone.scm.block.client.address</name><value>{{ template "flokkr.fullname" . }}-ozone-scm-0.{{ template "flokkr.fullname" . }}-ozone-scm</value></property>
    <property><name>ozone.om.address</name><value>{{ template "flokkr.fullname" . }}-ozone-om-0.{{ template "flokkr.fullname" . }}-ozone-om</value></property>
    <property><name>ozone.scm.client.address</name><value>{{ template "flokkr.fullname" . }}-ozone-scm-0.{{ template "flokkr.fullname" . }}-ozone-scm</value></property>
    <property><name>ozone.scm.names</name><value>{{ template "flokkr.fullname" . }}-ozone-scm-0.{{ template "flokkr.fullname" . }}-ozone-scm</value></property>
    <property><name>dfs.cblock.iscsi.advertised.ip</name><value>{{ .Values.service.iscsi.ClusterIp }}</value></property>
    <property><name>dfs.cblock.jscsi.cblock.server.address</name><value>{{ template "flokkr.fullname" . }}-quadra-master-0.{{ template "flokkr.fullname" . }}-quadra-master</value></property>
    <property><name>dfs.cblock.scm.ipaddress</name><value>{{ template "flokkr.fullname" . }}-ozone-scm-0.{{ template "flokkr.fullname" . }}-ozone-scm</value></property>
    {{- range $key, $value := .Values.config.ozoneSite }}
      <property><name>{{ $key }}</name><value>{{ $value }}</value></property>
    {{- end }}
    </configuration>
kind: ConfigMap
