apiVersion: v1
kind: Service
metadata:
  name: {{ template "flokkr.fullname" . }}-hdfs-namenode
  labels:
{{ include "flokkr.commonlabels" . | indent 4}}
spec:
  ports:
  - port: 50070
    name: web
  clusterIP: None
  selector:
     app: {{ template "flokkr.fullname" . }}
     component: hdfs-namenode
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "flokkr.fullname" . }}-hdfs-namenode
  labels:
{{ include "flokkr.commonlabels" . | indent 4}}
spec:
  serviceName: {{ template "flokkr.fullname" . }}-hdfs-namenode
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "flokkr.fullname" . }}
        component: hdfs-namenode
{{ include "flokkr.commonlabels" . | indent 8}}
{{ if .Values.features.prometheus }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
{{ end }}
    spec:
      shareProcessNamespace: true
      containers:
        - name: hdfs-namenode
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          args: ["hdfs","namenode"]
          env:
            - name: ENSURE_NAMENODE_DIR
              value: /data/namenode
{{ include "prometheus.jmx" . | indent 12}}
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
            - name: temp
              mountPath: "/tmp"
{{ if .Values.features.prometheus }}
        - name: jmxpromo
          image: flokkr/jmxpromo-sidecar
          volumeMounts:
             - name: temp
               mountPath: "/tmp"
{{end}}
      volumes:
        - name: config
          configMap:
            name: {{ template "flokkr.fullname" . }}-config
        - name: temp
          emptyDir:
             medium: Memory
