apiVersion: v1
kind: Service
metadata:
  name: {{ template "ozone.fullname" . }}-ksm
  labels:
    app: {{ template "ozone.fullname" . }}-ksm
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 9874
    name: web
  clusterIP: None
  selector:
     app: {{ template "ozone.fullname" . }}-ksm
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "ozone.fullname" . }}-ksm
spec:
  serviceName: {{ template "ozone.fullname" . }}-ksm
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "ozone.fullname" . }}-ksm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      containers:
        - name: ksm
          image: flokkr/hadoop:ozone
          args: ["hdfs","ksm"]
          env:
            - name: PROMETHEUSJMX_ENABLED
              value: "true"
            - name: PROMETHEUSJMX_AGENTOPTS
              value: port=28942
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: hadoopconf
