{{ if .Values.component.ozone }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "flokkr.fullname" . }}-ozone-om
  labels:
{{ include "flokkr.commonlabels" . | indent 6}}
spec:
  clusterIP: None
  ports:
  - port: 9874
    name: web
  selector:
     app: {{ template "flokkr.fullname" . }}
     component: ozone-om
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "flokkr.fullname" . }}-ozone-om
spec:
  serviceName: {{ template "flokkr.fullname" . }}-ozone-om
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        component: ozone-om
{{ include "flokkr.commonlabels" . | indent 8}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      containers:
        - name: ozone-om
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          args: ["ozone","om"]
          env:
            - name: SLEEP_SECONDS
              value: "30"
            - name: ENSURE_OM_INITIALIZED
              value: /data/metadata/ozoneManager/current/VERSION
{{ include "prometheus.jmx" . | indent 12}}
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "flokkr.fullname" . }}-config
{{end}}
