apiVersion: v1
kind: Service
metadata:
  name: {{ template "flokkr.fullname" . }}-ozone-datanode
  labels:
{{ include "flokkr.commonlabels" . | indent 6}}
spec:
  ports:
  - port: 9874
    name: web
  clusterIP: None
  selector:
     app: {{ template "flokkr.fullname" . }}
     component: ozone-datanode
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "flokkr.fullname" . }}-ozone-datanode
spec:
  serviceName: {{ template "flokkr.fullname" . }}-ozone-datanode
  replicas: {{ .Values.services.datanode.replicas }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        component: ozone-datanode
{{ include "flokkr.commonlabels" . | indent 8}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      serviceAccountName: {{ template "flokkr.fullname" . }}-configreloader
      containers:
        - name: ozone-datanode
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          args: ["ozone","datanode"]
          env:
            - name: KUBERNETES_CONFIGMAP_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: KUBERNETES_CONFIGMAP
              value: {{ template "flokkr.fullname" . }}-config
{{ include "prometheus.jmx" . | indent 12}}
