apiVersion: v1
kind: Service
metadata:
  name: {{ template "flokkr.fullname" . }}-ozone-scm
  labels:
{{ include "flokkr.commonlabels" . | indent 6}}
spec:
  clusterIP: None
  ports:
  - port: 9876
    name: web
  selector:
     app: {{ template "flokkr.fullname" . }}
     component: ozone-scm
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "flokkr.fullname" . }}-ozone-scm
spec:
  serviceName: {{ template "flokkr.fullname" . }}-ozone-scm
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        component: ozone-scm
{{ include "flokkr.commonlabels" . | indent 8}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      containers:
        - name: ozone-scm
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          args: ["oz","scm"]
          env:
            - name: ENSURE_SCM_INITIALIZED
              value: "/data/metadata/scm/current/VERSION"
{{ include "prometheus.jmx" . | indent 12}}
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "flokkr.fullname" . }}-config
