apiVersion: v1
kind: Service
metadata:
  name: {{ template "flokkr.fullname" . }}-quadra-master
  labels:
{{ include "flokkr.commonlabels" . | indent 4}}
spec:
  clusterIP: None
  ports:
  - port: 9876
    name: web
  selector:
     app: {{ template "flokkr.fullname" . }}
     component: quadra-master
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "flokkr.fullname" . }}-quadra-master
spec:
  serviceName: {{ template "flokkr.fullname" . }}-quadra-master
  replicas: 1
  template:
    metadata:
      labels:
        component: quadra-master
{{ include "flokkr.commonlabels" . | indent 8}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
{{ if .Values.serviceAccount }}
      serviceAccount: {{ .Values.serviceAccount }}
{{ end }}
      containers:
        - name: quadra-master
          image: {{ .Values.image.repository }}flokkr/hadoop:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          args: ["hdfs","cblockserver"]
          env:
{{ include "prometheus.jmx" . | indent 12}}
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "flokkr.fullname" . }}-config
