{{ if .Values.component.cblock }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "flokkr.fullname" . }}-quadra-target
  labels:
{{ include "flokkr.commonlabels" . | indent 4}}
spec:
  clusterIP: None
  ports:
  - port: 9876
    name: web
  selector:
     app: {{ template "flokkr.fullname" . }}
     component: quadra-target
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "flokkr.fullname" . }}-quadra-target
spec:
  serviceName: {{ template "flokkr.fullname" . }}-quadra-target
  replicas: 1
  template:
    metadata:
      labels:
        component: quadra-target
{{ include "flokkr.commonlabels" . | indent 8}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      containers:
        - name: quadra-target
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          args: ["oz","jscsi"]
          env:
{{ include "prometheus.jmx" . | indent 12}}
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "flokkr.fullname" . }}-config
{{end}}