{{ if .Values.component.ozone  }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "flokkr.fullname" . }}-ozone-scm-ingress
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /scm/
        backend:
          serviceName: {{ template "flokkr.fullname" . }}-ozone-scm
          servicePort: 9876
{{ end }}
