apiVersion: v1
kind: Service
metadata:
  name: {{ template "flokkr.fullname" . }}-zookeeper
  labels:
{{ include "flokkr.commonlabels" . | indent 6}}
spec:
  ports:
  - port: 9874
    name: web
  clusterIP: None
  selector:
     app: {{ template "flokkr.fullname" . }}
     component: zookeeper
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "flokkr.fullname" . }}-zookeeper
spec:
  serviceName: {{ template "flokkr.fullname" . }}-zookeeper
  replicas: {{ .Values.services.zookeeper.replicas }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        component: zookeeper
{{ include "flokkr.commonlabels" . | indent 8}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          env:
            - name: ZOOKEEPER_ID_FROM_HOST
              value: /data/zookeeper
{{- include "custom.env" . | indent 12}}
{{ include "prometheus.jmx" . | indent 12}}
          volumeMounts:
            - name: config
              mountPath: "/opt/zookeeper/conf"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "flokkr.fullname" . }}-config
