# Default values for ozone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#replicaCount: 1
image:
  tag: latest
#  repository: nginx
#  tag: stable
#  pullPolicy: IfNotPresent
#service:
#  name: nginx
#  type: ClusterIP
#  externalPort: 80
#  internalPort: 80
prometheus:
  enabled: false
  
ingress:
  enabled: true
  hosts:
    - chart-example.local
  annotations:
     traefik.frontend.rule.type: PathPrefixStrip
customEnvs: {}
