
image:
  tag: &tag ozone
  pullPolicy: Always
  repository: flokkr/hadoop
resources: {}

services:
   freon:
      replicas: 3
      args: 
        - ozone
        - freon
        - pk
        - --factor=THREE 
        - --replicationType=RATIS

dependencies:
   ozone: unknown
