
image:
  tag: &tag ozone
  pullPolicy: Always
  repository: flokkr/hadoop
resources: {}

services:
   freon:
      replicas: 3
      args: ["ozone", "freon", "-ratis", "3"]


dependencies:
   ozone: unknown
