apiVersion: v1
metadata:
  name: {{ template "flokkr.fullname" . }}-config
  labels:
{{ include "flokkr.commonlabels" . | indent 6}}
data:
  core-site.xml: |-
    <configuration>
      <property><name>fs.defaultFS</name><value>hdfs://{{ template "flokkr.fullname" . }}-hdfs-namenode-0.{{ template "flokkr.fullname" . }}-hdfs-namenode:9000</value></property>
      {{- range $key, $value := .Values.config.coreSite }}
        <property><name>{{ $key }}</name><value>{{ $value }}</value></property>
      {{- end }}
    </configuration>
  hdfs-site.xml: |-
    <configuration>
    <property><name>dfs.namenode.rpc-address</name><value>{{ template "flokkr.fullname" . }}-hdfs-namenode-0.{{ template "flokkr.fullname" . }}-hdfs-namenode:9000</value></property>
    {{- range $key, $value := .Values.config.hdfsSite }}
      <property><name>{{ $key }}</name><value>{{ $value }}</value></property>
    {{- end }}
    </configuration>
  log4j.properties: |-
    {{- range $key, $value := .Values.config.log4j }}
      {{ $key }}: {{ $value }}
    {{- end }}
kind: ConfigMap
