apiVersion: v1
kind: Service
metadata:
  name: {{ template "hdfs.fullname" . }}-datanode
  labels:
    app: {{ template "hdfs.fullname" . }}-datanode
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 9874
    name: web
  clusterIP: None
  selector:
     app: {{ template "hdfs.fullname" . }}-datanode
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "hdfs.fullname" . }}-datanode
spec:
  serviceName: {{ template "hdfs.fullname" . }}-datanode
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "hdfs.fullname" . }}-datanode
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      containers:
        - name: datanode
          image: flokkr/hadoop-hdfs-datanode:{{ .Values.image.tag }}
          env:
{{- if .Values.prometheus.enabled }}
            - name: PROMETHEUSJMX_ENABLED
              value: "true"
            - name: PROMETHEUSJMX_AGENTOPTS
              value: port=28942
{{- end -}}              
            {{- range $key, $value := .Values.customEnvs }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: hadoopconf
