iapiVersion: v1
kind: Service
metadata:
  name: {{ template "hdfs.fullname" . }}-namenode
  labels:
    app: {{ template "hdfs.fullname" . }}-namenode
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 50070
    name: web
  clusterIP: None
  selector:
     app: {{ template "hdfs.fullname" . }}-namenode
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "hdfs.fullname" . }}-namenode
spec:
  serviceName: {{ template "hdfs.fullname" . }}-namenode
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "hdfs.fullname" . }}-namenode
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      containers:
        - name: namenode
          image: flokkr/hadoop-hdfs-namenode:{{ .Values.image.tag }}
          env:
            - name: ENSURE_NAMENODE_DIR
              value: /data/namenode
{{- if .Values.prometheus.enabled }}
            - name: PROMETHEUSJMX_ENABLED
              value: "true"
            - name: PROMETHEUSJMX_AGENTOPTS
              value: port=28942
{{- end -}}
            {{- range $key, $value := .Values.customEnvs }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: hadoopconf
