image:
  tag: &tag ozone
  pullPolicy: Always
  repository: flokkr/hadoop

component:
   cblock: false
   hdsl: true
   ozone: true
service:
   iscsi:
      NodePort: 32060
      ClusterIp: 10.96.10.12

serviceAccount: cblock

features:
  storageclass: false
  prometheus: true

keel:
  policy: force
  trigger: poll
  pollSchedule: "@every 3m"
  images:
    - repository: image.repository
      tag: image.tag
