apiVersion: v1
metadata:
  name: {{ template "flokkr.fullname" . }}-conf
  labels:
{{ include "flokkr.commonlabels" . | indent 4}}
data:
  core-site.xml: |-
  <configuration>
    <property><name>fs.defaultFS</name><value>hdfs://{{ .Value.defaultFs }}</value></property>
  </configuration>
  yarn-site.xml: |-
    <configuration>
    <property><name>yarn.resourcemanager.hostname</name><value>{{ template "flokkr.fullname" . }}-resourcemanager-0.{{ template "flokkr.fullname" . }}-resourcemanager</value></property>
    <property><name>yarn.nodemanager.pmem-check-enabled</name><value>false</value></property>
    <property><name>yarn.nodemanager.delete.debug-delay-sec</name><value>600</value></property>
    <property><name>yarn.nodemanager.vmem-check-enabled</name><value>false</value></property>
    <property><name>yarn.nodemanager.aux-services</name><value>mapreduce_shuffle</value></property>
    <property><name>yarn.nodemanager.delete.thread-count</name><value>0</value></property>
    <property><name>yarn.nodemanager.local-dirs</name><value>/data/nodemanagerlocaldir</value></property>
    <property><name>yarn.nodemanager.log-dirs</name><value>/data/yarn-userlogs</value></property>
    <property><name>yarn.nodemanager.remote-app-log-dir</name><value>/data/yarn-remotelogs</value></property>
    <property><name>yarn.resourcemanager.bind-host</name><value>0.0.0.0</value></property>
    <property><name>yarn.nodemanager.bind-host</name><value>0.0.0.0</value></property>
    <property><name>yarn.scheduler.maximum-allocation-mb</name><value>12000</value></property>
    <property><name>yarn.nodemanager.resource.memory-mb</name><value>12000</value></property>
    </configuration>
  capacity-scheduler.xml: |-
    <configuration>
    <property><name>yarn.scheduler.capacity.node-locality-delay</name><value>40</value></property>
    <property><name>yarn.scheduler.capacity.root.default.user-limit-factor</name><value>1</value></property>
    <property><name>yarn.scheduler.capacity.root.default.acl_submit_applications</name><value>*</value></property>
    <property><name>yarn.scheduler.capacity.maximum-applications</name><value>10000</value></property>
    <property><name>yarn.scheduler.capacity.maximum-am-resource-percent</name><value>0.1</value></property>
    <property><name>yarn.scheduler.capacity.queue-mappings-override.enable</name><value>false</value></property>
    <property><name>yarn.scheduler.capacity.root.queues</name><value>default</value></property>
    <property><name>yarn.scheduler.capacity.root.default.state</name><value>RUNNING</value></property>
    <property><name>yarn.scheduler.capacity.queue-mappings</name><value></value></property>
    <property><name>yarn.scheduler.capacity.root.default.maximum-capacity</name><value>100</value></property>
    <property><name>yarn.scheduler.capacity.root.default.capacity</name><value>100</value></property>
    <property><name>yarn.scheduler.capacity.root.default.acl_administer_queue</name><value>*</value></property>
    <property><name>yarn.scheduler.capacity.resource-calculator</name><value>org.apache.hadoop.yarn.util.resource.DefaultResourceCalculator</value></property>
    </configuration>
kind: ConfigMap
