apiVersion: v1
kind: Service
metadata:
  name: {{ template "flokkr.fullname" . }}-nodemanager
  labels:
{{ include "flokkr.commonlabels" . | indent 4}}
spec:
  ports:
  - port: 8088
    name: web
  clusterIP: None
  selector:
     app: {{ template "flokkr.fullname" . }}
     component: nodemanager
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "flokkr.fullname" . }}-nodemanager
  labels:
{{ include "flokkr.commonlabels" . | indent 4}}
    component: nodemanager
spec:
  serviceName: {{ template "flokkr.fullname" . }}-nodemanager
  replicas: 1
  template:
    metadata:
      labels:
{{ include "flokkr.commonlabels" . | indent 8}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      containers:
        - name: nodemanager
          image: {{ .Values.image.repository }}flokkr/hadoop:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          args: ["yarn","nodemanager"]
          volumeMounts:
          - name: yarn-site
            mountPath: /opt/hadoop/etc/hadoop
          - name: hdfs-site
            mountPath: /opt/conf/hdfs-site
      volumes:
       - name: hdfs-site
         configMap:
           name: cblock-config
           items:
           - key: hdfs-site.xml
             path: hdfs-site.xml
       - name: yarn-site
         configMap:
           name: {{ template "flokkr.fullname" . }}-conf
           items:
           - key: yarn-site.xml
             path: yarn-site.xml
           - key: capacity-scheduler.xml
             path: capacity-scheduler.xml